apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: dev
    pod-security.kubernetes.io/enforce: privileged
  name: dev
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
