apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: test
    pod-security.kubernetes.io/enforce: restricted
  name: test
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
